version: '3.8'

services:
  redis_1:
    image: "docker.arvancloud.ir/redis:latest"
    volumes:
      - redis_1_data:/data
    configs:
      - source: redis_conf
        target: /usr/local/etc/redis/redis.conf
    command: >
      sh -c "EXTERNAL_IP=$(hostname -i | awk '{print \$1}') &&
      EXTERNAL_PORT=${REDIS_EXTERNAL_PORT:-6379} &&
      echo 'Starting Redis with replica announce IP: ${EXTERNAL_IP} and port: ${EXTERNAL_PORT}' &&
      exec redis-server /usr/local/etc/redis/redis.conf --replica-announce-ip ${EXTERNAL_IP} --replica-announce-port ${EXTERNAL_PORT}"
    networks:
      - redis_cluster_network
    deploy:
      placement:
        constraints:
          - node.hostname == node1  # Place on Node 1

  redis_2:
    image: "docker.arvancloud.ir/redis:latest"
    volumes:
      - redis_2_data:/data
    configs:
      - source: redis_conf
        target: /usr/local/etc/redis/redis.conf
    command: >
      sh -c "EXTERNAL_IP=$(hostname -i | awk '{print \$1}') &&
      EXTERNAL_PORT=${REDIS_EXTERNAL_PORT:-6379} &&
      echo 'Starting Redis with replica announce IP: ${EXTERNAL_IP} and port: ${EXTERNAL_PORT}' &&
      exec redis-server /usr/local/etc/redis/redis.conf --replica-announce-ip ${EXTERNAL_IP} --replica-announce-port ${EXTERNAL_PORT}"
    networks:
      - redis_cluster_network
    deploy:
      placement:
        constraints:
          - node.hostname == node1  # Place on Node 1, same as redis_1 (master)

  redis_3:
    image: "docker.arvancloud.ir/redis:latest"
    volumes:
      - redis_3_data:/data
    configs:
      - source: redis_conf
        target: /usr/local/etc/redis/redis.conf
    command: >
      sh -c "EXTERNAL_IP=$(hostname -i | awk '{print \$1}') &&
      EXTERNAL_PORT=${REDIS_EXTERNAL_PORT:-6379} &&
      echo 'Starting Redis with replica announce IP: ${EXTERNAL_IP} and port: ${EXTERNAL_PORT}' &&
      exec redis-server /usr/local/etc/redis/redis.conf --replica-announce-ip ${EXTERNAL_IP} --replica-announce-port ${EXTERNAL_PORT}"
    networks:
      - redis_cluster_network
    deploy:
      placement:
        constraints:
          - node.hostname == node2  # Place on Node 2

  redis_4:
    image: "docker.arvancloud.ir/redis:latest"
    volumes:
      - redis_4_data:/data
    configs:
      - source: redis_conf
        target: /usr/local/etc/redis/redis.conf
    command: >
      sh -c "EXTERNAL_IP=$(hostname -i | awk '{print \$1}') &&
      EXTERNAL_PORT=${REDIS_EXTERNAL_PORT:-6379} &&
      echo 'Starting Redis with replica announce IP: ${EXTERNAL_IP} and port: ${EXTERNAL_PORT}' &&
      exec redis-server /usr/local/etc/redis/redis.conf --replica-announce-ip ${EXTERNAL_IP} --replica-announce-port ${EXTERNAL_PORT}"
    networks:
      - redis_cluster_network
    deploy:
      placement:
        constraints:
          - node.hostname == node2  # Place on Node 2, same as redis_3 (master)

  redis_5:
    image: "docker.arvancloud.ir/redis:latest"
    volumes:
      - redis_5_data:/data
    configs:
      - source: redis_conf
        target: /usr/local/etc/redis/redis.conf
    command: >
      sh -c "EXTERNAL_IP=$(hostname -i | awk '{print \$1}') &&
      EXTERNAL_PORT=${REDIS_EXTERNAL_PORT:-6379} &&
      echo 'Starting Redis with replica announce IP: ${EXTERNAL_IP} and port: ${EXTERNAL_PORT}' &&
      exec redis-server /usr/local/etc/redis/redis.conf --replica-announce-ip ${EXTERNAL_IP} --replica-announce-port ${EXTERNAL_PORT}"
    networks:
      - redis_cluster_network
    deploy:
      placement:
        constraints:
          - node.hostname == node3  # Place on Node 3

  redis_6:
    image: "docker.arvancloud.ir/redis:latest"
    volumes:
      - redis_6_data:/data
    configs:
      - source: redis_conf
        target: /usr/local/etc/redis/redis.conf
    command: >
      sh -c "EXTERNAL_IP=$(hostname -i | awk '{print \$1}') &&
      EXTERNAL_PORT=${REDIS_EXTERNAL_PORT:-6379} &&
      echo 'Starting Redis with replica announce IP: ${EXTERNAL_IP} and port: ${EXTERNAL_PORT}' &&
      exec redis-server /usr/local/etc/redis/redis.conf --replica-announce-ip ${EXTERNAL_IP} --replica-announce-port ${EXTERNAL_PORT}"
    networks:
      - redis_cluster_network
    deploy:
      placement:
        constraints:
          - node.hostname == node3  # Place on Node 3, same as redis_5 (master)

  cluster_initiator:
    image: redis-cluster-initiator:latest
    tty: true
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    deploy:
      restart_policy:
        condition: none  # Do not restart after the task completes

      placement:
        constraints:
          - node.hostname == node1
    networks:
      - redis_cluster_network

  # redis_exporter:
  #   image: docker.arvancloud.ir/oliver006/redis_exporter:latest
  #   ports:
  #     - "9121:9121"
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.hostname == node1  # Place on Node 3

  #   command:
  #     - '--redis.addr=redis://redis_1:6379'
  #     - '--redis.addr=redis://redis_2:6379'
  #     - '--redis.addr=redis://redis_3:6379'
  #     - '--redis.addr=redis://redis_4:6379'
  #     - '--redis.addr=redis://redis_5:6379'
  #     - '--redis.addr=redis://redis_6:6379'
  #     - '--is-cluster=true'
  #   networks:
  #     redis_cluster_network:
  #       ipv4_address: 174.10.0.10
  # redis_commander:
  #   image: docker.arvancloud.ir/rediscommander/redis-commander:latest
  #   environment:
  #     REDIS_HOSTS: "local:redis_1:6379,local:redis_2:6379,local:redis_3:6379,local:redis_4:6379,local:redis_5:6379,local:redis_6:6379"
  #   ports:
  #     - "5050:8081"
  #   depends_on:
  #     - redis_1
  #     - redis_2
  #     - redis_3
  #     - redis_4
  #     - redis_5
  #     - redis_6
  #     - cluster_initiator
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.hostname == node1  # Place on Node 3, same as redis_5 (master)

  #   networks:
  #     redis_cluster_network:
  #       ipv4_address: 174.10.0.9
  # prometheus:
  #   image: docker.arvancloud.ir/prom/prometheus:latest
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus
  #   ports:
  #     - "9090:9090"
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.hostname == node1 # Place on Node 3

  #   networks:
  #     redis_cluster_network:
  #       ipv4_address: 174.10.0.11

  # grafana:
  #   image: docker.arvancloud.ir/grafana/grafana:latest
  #   volumes:
  #     - grafana_data5:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning  # Auto-configuration
  #   ports:
  #     - "3000:3000"
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.hostname == node1  # Place on Node 3

  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   depends_on:
  #     - prometheus
  #   networks:
  #     redis_cluster_network:
  #       ipv4_address: 174.10.0.12

networks:
  redis_cluster_network:
    external: true

configs:
  redis_conf:
    external: true

volumes:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}
