volumes:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}

services:
  redis_1:
    image: "redis:latest"
    ports:
      - "6381:6379"
    volumes:
      - redis_1_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.2

  redis_2:
    image: "redis:latest"
    ports:
      - "6382:6379"
    volumes:
      - redis_2_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.3

  redis_3:
    image: "redis:latest"
    ports:
      - "6383:6379"
    volumes:
      - redis_3_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.4

  redis_4:
    image: "redis:latest"
    ports:
      - "6384:6379"
    volumes:
      - redis_4_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.5

  redis_5:
    image: "redis:latest"
    ports:
      - "6385:6379"
    volumes:
      - redis_5_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.6

  redis_6:
    image: "redis:latest"
    ports:
      - "6386:6379"
    volumes:
      - redis_6_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.7

  # Ephemeral container to create the Redis cluster connections.
  # Once the setup is done, this container shuts down
  # and the cluster can be used by the service app container
  cluster_initiator:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.8

  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: "local:redis_1:6379,local:redis_2:6379,local:redis_3:6379,local:redis_4:6379,local:redis_5:6379,local:redis_6:6379"
    ports:
      - "5050:8081"
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
      - cluster_initiator
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.9

networks:
  redis_cluster_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 174.10.0.0/16
