volumes:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}
  prometheus_data: {}
  grafana_data5: {}

services:
  redis_1:
    image: "redis:latest"
    ports:
      - "6381:6379"
    volumes:
      - redis_1_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.2

  redis_2:
    image: "redis:latest"
    ports:
      - "6382:6379"
    volumes:
      - redis_2_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.3

  redis_3:
    image: "redis:latest"
    ports:
      - "6383:6379"
    volumes:
      - redis_3_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.4

  redis_4:
    image: "redis:latest"
    ports:
      - "6384:6379"
    volumes:
      - redis_4_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.5

  redis_5:
    image: "redis:latest"
    ports:
      - "6385:6379"
    volumes:
      - redis_5_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.6

  redis_6:
    image: "redis:latest"
    ports:
      - "6386:6379"
    volumes:
      - redis_6_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.7

  redis_exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    command:
      - '--redis.addr=redis://redis_1:6379'
      - '--redis.addr=redis://redis_2:6379'
      - '--redis.addr=redis://redis_3:6379'
      - '--redis.addr=redis://redis_4:6379'
      - '--redis.addr=redis://redis_5:6379'
      - '--redis.addr=redis://redis_6:6379'
      - '--is-cluster=true'
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.10

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.11

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data5:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning  # Auto-configuration
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.12

  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: "local:redis_1:6379,local:redis_2:6379,local:redis_3:6379,local:redis_4:6379,local:redis_5:6379,local:redis_6:6379"
    ports:
      - "5050:8081"
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    networks:
      redis_cluster_network:
        ipv4_address: 174.10.0.9

networks:
  redis_cluster_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 174.10.0.0/16
