global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'redis_cluster'
    metrics_path: /scrape
    static_configs:
      - targets:
          - redis://redis_1:6379
          - redis://redis_2:6379
          - redis://redis_3:6379
          - redis://redis_4:6379
          - redis://redis_5:6379
          - redis://redis_6:6379
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis_exporter:9121
